      SUBROUTINE TREMOV (IREC1,IREC2)
      IMPLICIT NONE
C----------
C BASE $Id$
C----------
C
C      SWITCH THE TREES FROM POSITION IREC1 AND POSITION IREC2.
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'ARRAYS.F77'
C
C
      INCLUDE 'ESTREE.F77'
C
C
      INCLUDE 'STDSTK.F77'
C
C
COMMONS
C
C----------
      REAL RTEM(36)
      INTEGER ITEM(15),IREC2,IREC1,IDMR,JDMR
C
      RTEM( 1) = BFV(IREC1)
      RTEM( 2) = CFV(IREC1)
      RTEM( 3) = MCFV(IREC1)
      RTEM( 4) = SCFV(IREC1)
      RTEM( 5) = DBH(IREC1)
      RTEM( 6) = DG(IREC1)
      RTEM( 7) = HT(IREC1)
      RTEM( 8) = HTG(IREC1)
      RTEM( 9) = OLDPCT(IREC1)
      RTEM(10) = OLDRN(IREC1)
      RTEM(11) = PCT(IREC1)
      RTEM(12) = WK1(IREC1)
      RTEM(13) = WK2(IREC1)
      RTEM(14) = WK3(IREC1)
      RTEM(15) = PROB(IREC1)
      RTEM(16) = ABIRTH(IREC1)
      RTEM(17) = ZRAND(IREC1)
      RTEM(18) = PTOCFV(IREC1)
      RTEM(19) = PMRCFV(IREC1)
      RTEM(20) = PSCFV(IREC1)
      RTEM(21) = PMRBFV(IREC1)
      RTEM(22) = PDBH(IREC1)
      RTEM(23) = PHT(IREC1)
      RTEM(24) = CRWDTH(IREC1)
      RTEM(25) = HT2TD(IREC1,1)
      RTEM(26) = HT2TD(IREC1,2)
      RTEM(27) = CULL(IREC1)
      RTEM(28) = ABVGRD_BIO(IREC1)
      RTEM(29) = MERCH_BIO(IREC1)
      RTEM(30) = CUBSAW_BIO(IREC1)
      RTEM(31) = FOLI_BIO(IREC1)
      RTEM(32) = ABVGRD_CARB(IREC1)
      RTEM(33) = MERCH_CARB(IREC1)
      RTEM(34) = CUBSAW_CARB(IREC1)
      RTEM(35) = FOLI_CARB(IREC1)
      RTEM(36) = CARB_FRAC(IREC1)

      ITEM( 1) = ICR(IREC1)
      ITEM( 2) = IMC(IREC1)
      ITEM( 3) = ISP(IREC1)
      ITEM( 4) = DEFECT(IREC1)
      ITEM( 5) = ISPECL(IREC1)
      ITEM( 6) = KUTKOD(IREC1)
      ITEM( 7) = ITRUNC(IREC1)
      ITEM( 8) = NORMHT(IREC1)
      ITEM( 9) = ITRE(IREC1)
      ITEM(10) = IESTAT(IREC1)
      ITEM(11) = IDTREE(IREC1)
      ITEM(12) = NCFDEF(IREC1)
      ITEM(13) = NBFDEF(IREC1)
      ITEM(14) = DECAYCD(IREC1)
      ITEM(15) = WDLDSTEM(IREC1)
C----------
      BFV(IREC1)    = BFV(IREC2)
      CFV(IREC1)    = CFV(IREC2)
      MCFV(IREC1)   = MCFV(IREC2)
      SCFV(IREC1)   = SCFV(IREC2)
      DBH(IREC1)    = DBH(IREC2)
      DG(IREC1)     = DG(IREC2)
      HT(IREC1)     = HT(IREC2)
      HTG(IREC1)    = HTG(IREC2)
      OLDPCT(IREC1) = OLDPCT(IREC2)
      OLDRN(IREC1)  = OLDRN(IREC2)
      PCT(IREC1)    = PCT(IREC2)
      WK1(IREC1)    = WK1(IREC2)
      WK2(IREC1)    = WK2(IREC2)
      WK3(IREC1)    = WK3(IREC2)
      ICR(IREC1)    = ICR(IREC2)
      IMC(IREC1)    = IMC(IREC2)
      ISP(IREC1)    = ISP(IREC2)
      DEFECT(IREC1) = DEFECT(IREC2)
      ISPECL(IREC1) = ISPECL(IREC2)
      KUTKOD(IREC1) = KUTKOD(IREC2)
      ITRUNC(IREC1) = ITRUNC(IREC2)
      NORMHT(IREC1) = NORMHT(IREC2)
      ITRE(IREC1)   = ITRE(IREC2)
      PROB(IREC1)   = PROB(IREC2)
      IESTAT(IREC1) = IESTAT(IREC2)
      ABIRTH(IREC1) = ABIRTH(IREC2)
      IDTREE(IREC1) = IDTREE(IREC2)
      ZRAND(IREC1)  = ZRAND(IREC2)
      PTOCFV(IREC1) = PTOCFV(IREC2)
      PMRCFV(IREC1) = PMRCFV(IREC2)
      PSCFV(IREC1) =  PSCFV(IREC2)
      PMRBFV(IREC1) = PMRBFV(IREC2)
      NCFDEF(IREC1) = NCFDEF(IREC2)
      NBFDEF(IREC1) = NBFDEF(IREC2)
      PDBH(IREC1)   = PDBH(IREC2)
      PHT(IREC1)    = PHT(IREC2)
      CRWDTH(IREC1) = CRWDTH(IREC2)
      HT2TD(IREC1,1)= HT2TD(IREC2,1)
      HT2TD(IREC1,2)= HT2TD(IREC2,2)
      CULL(IREC1)   = CULL(IREC2)
      DECAYCD(IREC1) = DECAYCD(IREC2)
      WDLDSTEM(IREC1) = WDLDSTEM(IREC2)
      ABVGRD_BIO(IREC1) = ABVGRD_BIO(IREC2)
      MERCH_BIO(IREC1) = MERCH_BIO(IREC2)
      CUBSAW_BIO(IREC1) = CUBSAW_BIO(IREC2)
      FOLI_BIO(IREC1) = FOLI_BIO(IREC2)
      ABVGRD_CARB(IREC1) = ABVGRD_CARB(IREC2)
      MERCH_CARB(IREC1) = MERCH_CARB(IREC2)
      CUBSAW_CARB(IREC1) = CUBSAW_CARB(IREC2)
      FOLI_CARB(IREC1) = FOLI_CARB(IREC2)
      CARB_FRAC(IREC1) = CARB_FRAC(IREC2)
C----------
C  ZERO OUT IREC2 POSITION
C----------
      BFV(IREC2)         = RTEM( 1)
      CFV(IREC2)         = RTEM( 2)
      MCFV(IREC2)        = RTEM( 3)
      SCFV(IREC2)        = RTEM( 4)
      DBH(IREC2)         = RTEM( 5)
      DG(IREC2)          = RTEM( 6)
      HT(IREC2)          = RTEM( 7)
      HTG(IREC2)         = RTEM( 8)
      OLDPCT(IREC2)      = RTEM( 9)
      OLDRN(IREC2)       = RTEM(10)
      PCT(IREC2)         = RTEM(11)
      WK1(IREC2)         = RTEM(12)
      WK2(IREC2)         = RTEM(13)
      WK3(IREC2)         = RTEM(14)
      PROB(IREC2)        = RTEM(15)
      ABIRTH(IREC2)      = RTEM(16)
      ZRAND(IREC2)       = RTEM(17)
      PTOCFV(IREC2)      = RTEM(18)
      PMRCFV(IREC2)      = RTEM(19)
      PSCFV(IREC2)       = RTEM(20)
      PMRBFV(IREC2)      = RTEM(21)
      PDBH(IREC2)        = RTEM(22)
      PHT(IREC2)         = RTEM(23)
      CRWDTH(IREC2)      = RTEM(24)
      HT2TD(IREC2,1)     = RTEM(25)
      HT2TD(IREC2,2)     = RTEM(26)
      CULL(IREC2)        = RTEM(27)
      ABVGRD_BIO(IREC2)  = RTEM(28)
      MERCH_BIO(IREC2)   = RTEM(29)
      CUBSAW_BIO(IREC2)  = RTEM(30)
      FOLI_BIO(IREC2)    = RTEM(31)
      ABVGRD_CARB(IREC2) = RTEM(32)
      MERCH_CARB(IREC2)  = RTEM(33)
      CUBSAW_CARB(IREC2) = RTEM(34)
      FOLI_CARB(IREC2)   = RTEM(35)
      CARB_FRAC(IREC2)   = RTEM(36)

      ICR(IREC2)    = ITEM( 1)
      IMC(IREC2)    = ITEM( 2)
      ISP(IREC2)    = ITEM( 3)
      DEFECT(IREC2) = ITEM( 4)
      ISPECL(IREC2) = ITEM( 5)
      KUTKOD(IREC2) = ITEM( 6)
      ITRUNC(IREC2) = ITEM( 7)
      NORMHT(IREC2) = ITEM( 8)
      ITRE(IREC2)   = ITEM( 9)
      IESTAT(IREC2) = ITEM(10)
      IDTREE(IREC2) = ITEM(11)
      NCFDEF(IREC2) = ITEM(12)
      NBFDEF(IREC2) = ITEM(13)
      DECAYCD(IREC2)= ITEM(14)
      WDLDSTEM(IREC2)=ITEM(15)
C----------
C  GET MISTLETOE RATING FROM POSITION IREC2 AND PUT IT AT IEND.
C----------
      CALL MISGET(IREC2,IDMR)
      CALL MISGET(IREC1,JDMR)
      CALL MISPUT(IREC2,JDMR)
      CALL MISPUT(IREC1,IDMR)
C
      RETURN
      END
